### ISSUE TITLE
Feature - Filtering records

### ISSUE THREAD

**Issue by nw-go** [codernayeem/rec-analyzer#1]
Now, it only has a system for viewing records. But, what if we wanted to **filter** them.

### It can be filtered based on:
  - Call date
  - Call time
  - Call number
  - Outgoing or Ingoing calls

**Comment by codernayeem** [comment]
**Filter** Feature is on the way ...

**Comment by codernayeem** [comment]
Filter Feature has been added. More update coming soon ...
